name: android

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: android-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-apk:
    uses: ./.github/workflows/apk-build.yml
    secrets: inherit
